/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.realm;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import android.content.Context;

// This proxy can be created by calling Tirealm.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = RealmModule.class)
public class ObjectProxy extends KrollProxy {
	// Standard Debugging variables
	private static final String LCAT = "RealM";
	RObject rObject;
	Context context = TiApplication.getInstance().getApplicationContext();

	// Constructor
	public ObjectProxy() {
		super();
	}

	// Handle creation options
	@Override
	public void handleCreationArgs(KrollModule createdInModule, Object[] args) {
		// validation of inputs;
		if (!(args[0] instanceof String)) {
			Log.e(LCAT, "First paramater must be a string");
			return;
		}
		if (!(args[1] instanceof KrollDict)) {
			Log.e(LCAT, "Second paramater must be an object");
			return;
		}
		String className = (String) args[0];
		KrollDict options = (KrollDict) args[1];
		for (String key : options.keySet()) {
			// keys are property names of class

		}

		rObject = new RObject();
		init(context);
		// Get a Realm instance for this thread
		Realm realm = Realm.getDefaultInstance();

		super.handleCreationArgs(createdInModule, args);
	}
}